{
 "title": "External Scan",
 "tags": [ "custom" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Scan Results",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "name",
     "bucketAggs": [
      {
       "field": "info.severity.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info.severity.keyword:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Detections",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "info.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Scan Frequency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Findings Table",
   "type": "table",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "matched-at.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "info.name.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "info.severity.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info.severity.keyword: *",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}