apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  releaseName: grafana
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      version: "8.6.0"
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values
      valuesKey: values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  releaseName: elastic
  interval: 1m
  chart:
    spec:
      chart: elasticsearch
      sourceRef:
        kind: HelmRepository
        name: elastic-repo
        namespace: flux-system
      version: "8.5.1"
  valuesFrom:
    - kind: ConfigMap
      name: elastic-values
      valuesKey: values.yaml