apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - releases/secret.yaml               
  - configmaps/config.yaml 
  - configmaps/dashboards.yaml
  - repositories/fluxcd-repositories.yaml  
  - releases/helmreleases.yaml
  - releases/scanner.yaml     
 