apiVersion: v1
kind: ConfigMap
metadata:
  name: subfinder-config
  namespace: monitoring  # Change to your namespace if different
data:
  provider-config.yaml: |
    # Your configuration here
    virustotal:
      - API_KEY

    shodan:
      - API_KEY
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudscan-config
  namespace: monitoring
data:
  config.toml: |
    # Example configuration settings
    [settings]
    targets = ["target.com"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudscan
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudscan
  template:
    metadata:
      labels:
        app: cloudscan
    spec:
      containers:
        - name: cloudscan
          image: tdub17/cloudscan:latest
          env:
            - name: ELASTIC_HOST
              value: "elasticsearch-master"  # Set the value for ELASTIC_HOST here
          volumeMounts:
            - name: config-volume
              mountPath: /home/cloudscan/.config/subfinder/provider-config.yaml
              subPath: provider-config.yaml
            - name: cloudscan-config-volume
              mountPath: /home/cloudscan/app/config.toml
              subPath: config.toml
      volumes:
        - name: config-volume
          configMap:
            name: subfinder-config
        - name: cloudscan-config-volume
          configMap:
            name: cloudscan-config
