apiVersion: v1
kind: ConfigMap
metadata:
  name: subfinder-config
  namespace: monitoring  # Change to your namespace if different
data:
  provider-config.yaml: |
    # Your configuration here
    virustotal: 
      - "your-api-key"
    shodan:
      - "your-api-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudscan
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudscan
  template:
    metadata:
      labels:
        app: cloudscan
    spec:
      containers:
        - name: cloudscan
          image: tdub17/cloudscan:latest
          volumeMounts:
            - name: config-volume
              mountPath: /home/cloudscan/.config/subfinder/provider-config.yaml
              subPath: provider-config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: subfinder-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-scan
  namespace: monitoring
data:
  dashboard.json: |
    {{ (.Files.Get "dashboards/dashboard.json") | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: monitoring
type: Opaque
data:
  username: ZWxhc3RpYwo=
  password: ZWxhc3RpYwo=
---
apiVersion: helm.sh/v1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  chart:
    repository: https://helm.elastic.co
    name: elasticsearch
  values:
    - elasticvalues.yml  # Reference the values file for Elasticsearch configuration
---
apiVersion: helm.sh/v1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  chart:
    repository: https://grafana.github.io/helm-charts
    name: loki-stack
  values:
    - lokivalues.yml  # Reference the values file for Loki stack configuration
