# Loki configuration
loki:
  auth_enabled: false

  pattern_ingester:
    enabled: true

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      shared_store: filesystem
      cache_location: /var/loki/cache
    filesystem:
      directory: /var/loki/chunks

  schema_config:
    configs:
      - from: 2023-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 168h

  server:
    http_listen_port: 3100

  memberlist:
    join_members: ["loki-memberlist"]

  compactor:
    working_directory: /var/loki/compactor
    shared_store: filesystem

# Grafana configuration
grafana:
  enabled: true
  service:
    type: ClusterIP
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin

  plugins:
    - grafana-lokiexplore-app

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-stack:3100 # Adjust the URL based on your Loki service name and port
          isDefault: true
          jsonData:
            maxLines: 1000
        - name: Elasticsearch
          type: elasticsearch
          url: https://elasticsearch-master:9200
          access: proxy
          basicAuth: true
          basicAuthUser: "elastic"          # Set the username
          secureJsonData:
            basicAuthPassword: "elastic"    # Set the password
          jsonData:
            tlsSkipVerify: true             # Skip TLS verification
            esVersion: 7                    # Elasticsearch version (adjust if needed)
            timeField: "@timestamp"         # Default timestamp field for Elasticsearch
            index: "domains-*"              # Set the index pattern

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'External Scans'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          updateIntervalSeconds: 10
          options:
            path: /var/lib/grafana/dashboards
            foldersFromFilesStructure: true

  extraConfigmapMounts: 
    - name: external-scan
      mountPath: /var/lib/grafana/dashboards
      subPath: ""
      configMap: external-scan
      readOnly: true
      optional: false

  # dashboards:
  #   default:
  #     detections:
  #       json: |
  #         {
  #         "id": null,
  #         "uid": "detections",
  #         "title": "Detections",
  #         "tags": ["custom"],
  #         "timezone": "browser",
  #         "schemaVersion": 16,
  #         "version": 0,
  #         "panels": [
  #         {
  #         "datasource": {
  #           "type": "elasticsearch",
  #           "uid": "P31C819B24CF3C3C7"
  #         },
  #         "fieldConfig": {
  #           "defaults": {
  #             "color": {
  #               "mode": "thresholds"
  #             },
  #             "mappings": [],
  #             "thresholds": {
  #               "mode": "absolute",
  #               "steps": [
  #                 {
  #                   "color": "green",
  #                   "value": null
  #                 }
  #               ]
  #             }
  #           },
  #           "overrides": []
  #         },
  #         "gridPos": {
  #           "h": 9,
  #           "w": 11,
  #           "x": 0,
  #           "y": 0
  #         },
  #         "id": 1,
  #         "options": {
  #           "displayMode": "lcd",
  #           "legend": {
  #             "calcs": [],
  #             "displayMode": "list",
  #             "placement": "bottom",
  #             "showLegend": false
  #           },
  #           "maxVizHeight": 300,
  #           "minVizHeight": 16,
  #           "minVizWidth": 8,
  #           "namePlacement": "auto",
  #           "orientation": "horizontal",
  #           "reduceOptions": {
  #             "calcs": [
  #               "lastNotNull"
  #             ],
  #             "fields": "",
  #             "values": true
  #           },
  #           "showUnfilled": true,
  #           "sizing": "auto",
  #           "valueMode": "color"
  #         },
  #         "pluginVersion": "11.3.0",
  #         "targets": [
  #           {
  #             "alias": "",
  #             "bucketAggs": [
  #               {
  #                 "field": "info.name.keyword",
  #                 "id": "2",
  #                 "settings": {
  #                   "min_doc_count": "1",
  #                   "order": "asc",
  #                   "orderBy": "_term",
  #                   "size": "0"
  #                 },
  #                 "type": "terms"
  #               }
  #             ],
  #             "datasource": {
  #               "type": "elasticsearch",
  #               "uid": "P31C819B24CF3C3C7"
  #             },
  #             "hide": false,
  #             "metrics": [
  #               {
  #                 "id": "1",
  #                 "type": "count"
  #               }
  #             ],
  #             "query": "",
  #             "refId": "A",
  #             "timeField": "@timestamp"
  #           }
  #         ],
  #         "title": "Detections",
  #         "type": "bargauge"
  #         }
  #         ],
  #         "preload": false,
  #         "templating": {
  #         "list": []
  #         },
  #         "time": {
  #         "from": "now-24h",
  #         "to": "now"
  #         },
  #         "timepicker": {},
  #         "weekStart": ""
  #         }
  #     scan-frequency-dashboard:
  #       json: |
  #         {
  #         "id": null,
  #         "uid": "scan-frequency",
  #         "title": "Scan Frequency",
  #         "tags": ["custom"],
  #         "timezone": "browser",
  #         "schemaVersion": 16,
  #         "version": 0,
  #         "panels": [
  #         {
  #         "datasource": {
  #         "type": "elasticsearch",
  #         "uid": "P31C819B24CF3C3C7"
  #         },
  #         "fieldConfig": {
  #         "defaults": {
  #           "color": {
  #             "mode": "palette-classic"
  #           },
  #           "custom": {
  #             "axisBorderShow": false,
  #             "axisCenteredZero": false,
  #             "axisColorMode": "text",
  #             "axisLabel": "",
  #             "axisPlacement": "auto",
  #             "barAlignment": 0,
  #             "barWidthFactor": 0.6,
  #             "drawStyle": "line",
  #             "fillOpacity": 0,
  #             "gradientMode": "none",
  #             "hideFrom": {
  #               "legend": false,
  #               "tooltip": false,
  #               "viz": false
  #             },
  #             "insertNulls": false,
  #             "lineInterpolation": "linear",
  #             "lineWidth": 1,
  #             "pointSize": 5,
  #             "scaleDistribution": {
  #               "type": "linear"
  #             },
  #             "showPoints": "auto",
  #             "spanNulls": false,
  #             "stacking": {
  #               "group": "A",
  #               "mode": "none"
  #             },
  #             "thresholdsStyle": {
  #               "mode": "off"
  #             }
  #           },
  #           "mappings": [],
  #           "thresholds": {
  #             "mode": "absolute",
  #             "steps": [
  #               {
  #                 "color": "green",
  #                 "value": null
  #               },
  #               {
  #                 "color": "red",
  #                 "value": 80
  #               }
  #             ]
  #           }
  #         },
  #         "overrides": []
  #         },
  #         "gridPos": {
  #         "h": 8,
  #         "w": 12,
  #         "x": 0,
  #         "y": 0
  #         },
  #         "id": 1,
  #         "options": {
  #         "legend": {
  #           "calcs": [],
  #           "displayMode": "list",
  #           "placement": "bottom",
  #           "showLegend": true
  #         },
  #         "tooltip": {
  #           "mode": "single",
  #           "sort": "none"
  #         }
  #         },
  #         "pluginVersion": "11.3.0",
  #         "targets": [
  #         {
  #           "alias": "",
  #           "bucketAggs": [
  #             {
  #               "field": "@timestamp",
  #               "id": "2",
  #               "settings": {
  #                 "interval": "auto"
  #               },
  #               "type": "date_histogram"
  #             }
  #           ],
  #           "datasource": {
  #             "type": "elasticsearch",
  #             "uid": "P31C819B24CF3C3C7"
  #           },
  #           "metrics": [
  #             {
  #               "id": "1",
  #               "type": "count"
  #             }
  #           ],
  #           "query": "",
  #           "refId": "A",
  #           "timeField": "@timestamp"
  #         }
  #         ],
  #         "title": "Scan Frequency",
  #         "type": "timeseries"
  #         }
  #         ],
  #         "preload": false,
  #         "templating": {
  #         "list": []
  #         },
  #         "time": {
  #         "from": "now-24h",
  #         "to": "now"
  #         }
  #         }

  #     scan-results-dashboard:
  #       json: |
  #         {
  #         "id": null,
  #         "uid": "scan-results",
  #         "title": "Scan Results",
  #         "tags": ["custom"],
  #         "timezone": "browser",
  #         "schemaVersion": 16,
  #         "version": 0,
  #         "panels": [
  #         {
  #         "datasource": {
  #         "type": "elasticsearch",
  #         "uid": "P31C819B24CF3C3C7"
  #         },
  #         "fieldConfig": {
  #         "defaults": {
  #         "color": {
  #         "mode": "palette-classic"
  #         },
  #         "custom": {
  #         "axisBorderShow": false,
  #         "axisCenteredZero": false,
  #         "axisColorMode": "text",
  #         "axisLabel": "",
  #         "axisPlacement": "auto",
  #         "fillOpacity": 80,
  #         "gradientMode": "none",
  #         "hideFrom": {
  #         "legend": false,
  #         "tooltip": false,
  #         "viz": false
  #         },
  #         "lineWidth": 1,
  #         "scaleDistribution": {
  #         "type": "linear"
  #         },
  #         "thresholdsStyle": {
  #         "mode": "off"
  #         }
  #         },
  #         "mappings": [
  #         {
  #         "options": {
  #         "critical": {
  #         "color": "dark-red",
  #         "index": 4,
  #         "text": "Critical"
  #         },
  #         "high": {
  #         "color": "dark-orange",
  #         "index": 3,
  #         "text": "High"
  #         },
  #         "info": {
  #         "color": "blue",
  #         "index": 0,
  #         "text": "Info"
  #         },
  #         "low": {
  #         "color": "dark-green",
  #         "index": 1,
  #         "text": "Low"
  #         },
  #         "medium": {
  #         "color": "dark-yellow",
  #         "index": 2,
  #         "text": "Medium"
  #         }
  #         },
  #         "type": "value"
  #         }
  #         ],
  #         "thresholds": {
  #         "mode": "absolute",
  #         "steps": [
  #         {
  #         "color": "green",
  #         "value": null
  #         }
  #         ]
  #         },
  #         "unitScale": true
  #         },
  #         "overrides": []
  #         },
  #         "gridPos": {
  #         "h": 9,
  #         "w": 11,
  #         "x": 0,
  #         "y": 0
  #         },
  #         "id": 1,
  #         "options": {
  #         "barRadius": 0,
  #         "barWidth": 0.97,
  #         "colorByField": "info.severity.keyword",
  #         "fullHighlight": false,
  #         "groupWidth": 0.7,
  #         "legend": {
  #         "calcs": [],
  #         "displayMode": "list",
  #         "placement": "bottom",
  #         "showLegend": true
  #         },
  #         "orientation": "horizontal",
  #         "showValue": "auto",
  #         "stacking": "none",
  #         "tooltip": {
  #         "mode": "single",
  #         "sort": "none"
  #         },
  #         "xField": "info.severity.keyword",
  #         "xTickLabelRotation": 0,
  #         "xTickLabelSpacing": 0
  #         },
  #         "targets": [
  #         {
  #         "alias": "name",
  #         "bucketAggs": [
  #         {
  #         "field": "info.severity.keyword",
  #         "id": "2",
  #         "settings": {
  #         "min_doc_count": "1",
  #         "order": "desc",
  #         "orderBy": "_term",
  #         "size": "10"
  #         },
  #         "type": "terms"
  #         }
  #         ],
  #         "datasource": {
  #         "type": "elasticsearch",
  #         "uid": "P31C819B24CF3C3C7"
  #         },
  #         "metrics": [
  #         {
  #         "id": "1",
  #         "type": "count"
  #         }
  #         ],
  #         "query": "info.severity.keyword:*",
  #         "refId": "A",
  #         "timeField": "@timestamp"
  #         }
  #         ],
  #         "title": "Scan Results",
  #         "type": "barchart"
  #         }
  #         ],
  #         "refresh": "",
  #         "templating": {
  #         "list": []
  #         },
  #         "time": {
  #         "from": "now-24h",
  #         "to": "now"
  #         },
  #         "timepicker": {},
  #         "weekStart": ""
  #         }

