apiVersion: v1
kind: ConfigMap
metadata:
  name: subfinder-config
  namespace: monitoring  # Change to your namespace if different
data:
  provider-config.yaml: |
    # Your configuration here
    virustotal:
      - API_KEY

    shodan:
      - API_KEY
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudscan-config
  namespace: monitoring
data:
  config.toml: |
    # Example configuration settings
    [settings]
    targets = ["domain.com"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudscan
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudscan
  template:
    metadata:
      labels:
        app: cloudscan
    spec:
      hostNetwork: true
      containers:
        - name: cloudscan
          image: tdub17/cloudscan:latest
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 4
              memory: 8Gi
          # env:
          #   - name: ELASTIC_HOST
          #     value: "elasticsearch-master.monitoring.svc.cluster.local"  # use the FQDN due to host networking needs.
          volumeMounts:
            - name: config-volume
              mountPath: /home/cloudscan/.config/subfinder/provider-config.yaml
              subPath: provider-config.yaml
            - name: cloudscan-config-volume
              mountPath: /home/cloudscan/.config/cloudscan/config.toml
              subPath: config.toml
      volumes:
        - name: config-volume
          configMap:
            name: subfinder-config
        - name: cloudscan-config-volume
          configMap:
            name: cloudscan-config
    